# -*- coding: utf-8 -*-
"""Homework3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HR7d63qEpw3y24nSZUR_7F-bPCiWGiCX
"""

import numpy as np
import matplotlib.pyplot as plt
from IPython.display import clear_output # Only for iPython
# from google.colab import files

"""#Helper function"""

def crossMat(a):
    """
    Returns the cross product matrix of vector 'a'.

    Parameters:
    a : np.ndarray
        A 3-element array representing a vector.

    Returns:
    A : np.ndarray
        The cross product matrix corresponding to vector 'a'.
    """
    A = np.array([[0, -a[2], a[1]],
                  [a[2], 0, -a[0]],
                  [-a[1], a[0], 0]])

    return A

"""#Gradient and Hessian of elastic energies"""

def gradEb(xkm1, ykm1, xk, yk, xkp1, ykp1, curvature0, l_k, EI):
    """
    Returns the derivative of bending energy E_k^b with respect to
    x_{k-1}, y_{k-1}, x_k, y_k, x_{k+1}, and y_{k+1}.

    Parameters:
    xkm1, ykm1 : float
        Coordinates of the previous node (x_{k-1}, y_{k-1}).
    xk, yk : float
        Coordinates of the current node (x_k, y_k).
    xkp1, ykp1 : float
        Coordinates of the next node (x_{k+1}, y_{k+1}).
    curvature0 : float
        Discrete natural curvature at node (xk, yk).
    l_k : float
        Voronoi length of node (xk, yk).
    EI : float
        Bending stiffness.

    Returns:
    dF : np.ndarray
        Derivative of bending energy.
    """

    # Nodes in 3D
    node0 = np.array([xkm1, ykm1, 0.0])
    node1 = np.array([xk, yk, 0])
    node2 = np.array([xkp1, ykp1, 0])

    # Unit vectors along z-axis
    m2e = np.array([0, 0, 1])
    m2f = np.array([0, 0, 1])

    kappaBar = curvature0

    # Initialize gradient of curvature
    gradKappa = np.zeros(6)

    # Edge vectors
    ee = node1 - node0
    ef = node2 - node1

    # Norms of edge vectors
    norm_e = np.linalg.norm(ee)
    norm_f = np.linalg.norm(ef)

    # Unit tangents
    te = ee / norm_e
    tf = ef / norm_f

    # Curvature binormal
    kb = 2.0 * np.cross(te, tf) / (1.0 + np.dot(te, tf))

    chi = 1.0 + np.dot(te, tf)
    tilde_t = (te + tf) / chi
    tilde_d2 = (m2e + m2f) / chi

    # Curvature
    kappa1 = kb[2]

    # Gradient of kappa1 with respect to edge vectors
    Dkappa1De = 1.0 / norm_e * (-kappa1 * tilde_t + np.cross(tf, tilde_d2))
    Dkappa1Df = 1.0 / norm_f * (-kappa1 * tilde_t - np.cross(te, tilde_d2))

    # Populate the gradient of kappa
    gradKappa[0:2] = -Dkappa1De[0:2]
    gradKappa[2:4] = Dkappa1De[0:2] - Dkappa1Df[0:2]
    gradKappa[4:6] = Dkappa1Df[0:2]

    # Gradient of bending energy
    dkappa = kappa1 - kappaBar
    dF = gradKappa * EI * dkappa / l_k

    return dF

def hessEb(xkm1, ykm1, xk, yk, xkp1, ykp1, curvature0, l_k, EI):
    """
    Returns the Hessian (second derivative) of bending energy E_k^b
    with respect to x_{k-1}, y_{k-1}, x_k, y_k, x_{k+1}, and y_{k+1}.

    Parameters:
    xkm1, ykm1 : float
        Coordinates of the previous node (x_{k-1}, y_{k-1}).
    xk, yk : float
        Coordinates of the current node (x_k, y_k).
    xkp1, ykp1 : float
        Coordinates of the next node (x_{k+1}, y_{k+1}).
    curvature0 : float
        Discrete natural curvature at node (xk, yk).
    l_k : float
        Voronoi length of node (xk, yk).
    EI : float
        Bending stiffness.

    Returns:
    dJ : np.ndarray
        Hessian of bending energy.
    """

    # Nodes in 3D
    node0 = np.array([xkm1, ykm1, 0])
    node1 = np.array([xk, yk, 0])
    node2 = np.array([xkp1, ykp1, 0])

    # Unit vectors along z-axis
    m2e = np.array([0, 0, 1])
    m2f = np.array([0, 0, 1])

    kappaBar = curvature0

    # Initialize gradient of curvature
    gradKappa = np.zeros(6)

    # Edge vectors
    ee = node1 - node0
    ef = node2 - node1

    # Norms of edge vectors
    norm_e = np.linalg.norm(ee)
    norm_f = np.linalg.norm(ef)

    # Unit tangents
    te = ee / norm_e
    tf = ef / norm_f

    # Curvature binormal
    kb = 2.0 * np.cross(te, tf) / (1.0 + np.dot(te, tf))

    chi = 1.0 + np.dot(te, tf)
    tilde_t = (te + tf) / chi
    tilde_d2 = (m2e + m2f) / chi

    # Curvature
    kappa1 = kb[2]

    # Gradient of kappa1 with respect to edge vectors
    Dkappa1De = 1.0 / norm_e * (-kappa1 * tilde_t + np.cross(tf, tilde_d2))
    Dkappa1Df = 1.0 / norm_f * (-kappa1 * tilde_t - np.cross(te, tilde_d2))

    # Populate the gradient of kappa
    gradKappa[0:2] = -Dkappa1De[0:2]
    gradKappa[2:4] = Dkappa1De[0:2] - Dkappa1Df[0:2]
    gradKappa[4:6] = Dkappa1Df[0:2]

    # Compute the Hessian (second derivative of kappa)
    DDkappa1 = np.zeros((6, 6))

    norm2_e = norm_e**2
    norm2_f = norm_f**2

    Id3 = np.eye(3)

    # Helper matrices for second derivatives
    tt_o_tt = np.outer(tilde_t, tilde_t)
    tmp = np.cross(tf, tilde_d2)
    tf_c_d2t_o_tt = np.outer(tmp, tilde_t)
    kb_o_d2e = np.outer(kb, m2e)

    D2kappa1De2 = (2 * kappa1 * tt_o_tt - tf_c_d2t_o_tt - tf_c_d2t_o_tt.T) / norm2_e - \
                  kappa1 / (chi * norm2_e) * (Id3 - np.outer(te, te)) + \
                  (kb_o_d2e + kb_o_d2e.T) / (4 * norm2_e)

    tmp = np.cross(te, tilde_d2)
    te_c_d2t_o_tt = np.outer(tmp, tilde_t)
    tt_o_te_c_d2t = te_c_d2t_o_tt.T
    kb_o_d2f = np.outer(kb, m2f)

    D2kappa1Df2 = (2 * kappa1 * tt_o_tt + te_c_d2t_o_tt + te_c_d2t_o_tt.T) / norm2_f - \
                  kappa1 / (chi * norm2_f) * (Id3 - np.outer(tf, tf)) + \
                  (kb_o_d2f + kb_o_d2f.T) / (4 * norm2_f)
    D2kappa1DeDf = -kappa1 / (chi * norm_e * norm_f) * (Id3 + np.outer(te, tf)) \
                  + 1.0 / (norm_e * norm_f) * (2 * kappa1 * tt_o_tt - tf_c_d2t_o_tt + \
                  tt_o_te_c_d2t - crossMat(tilde_d2))
    D2kappa1DfDe = D2kappa1DeDf.T

    # Populate the Hessian of kappa
    DDkappa1[0:2, 0:2] = D2kappa1De2[0:2, 0:2]
    DDkappa1[0:2, 2:4] = -D2kappa1De2[0:2, 0:2] + D2kappa1DeDf[0:2, 0:2]
    DDkappa1[0:2, 4:6] = -D2kappa1DeDf[0:2, 0:2]
    DDkappa1[2:4, 0:2] = -D2kappa1De2[0:2, 0:2] + D2kappa1DfDe[0:2, 0:2]
    DDkappa1[2:4, 2:4] = D2kappa1De2[0:2, 0:2] - D2kappa1DeDf[0:2, 0:2] - \
                         D2kappa1DfDe[0:2, 0:2] + D2kappa1Df2[0:2, 0:2]
    DDkappa1[2:4, 4:6] = D2kappa1DeDf[0:2, 0:2] - D2kappa1Df2[0:2, 0:2]
    DDkappa1[4:6, 0:2] = -D2kappa1DfDe[0:2, 0:2]
    DDkappa1[4:6, 2:4] = D2kappa1DfDe[0:2, 0:2] - D2kappa1Df2[0:2, 0:2]
    DDkappa1[4:6, 4:6] = D2kappa1Df2[0:2, 0:2]

    # Hessian of bending energy
    dkappa = kappa1 - kappaBar
    dJ = 1.0 / l_k * EI * np.outer(gradKappa, gradKappa)
    dJ += 1.0 / l_k * dkappa * EI * DDkappa1

    return dJ

def gradEs(xk, yk, xkp1, ykp1, l_k, EA):
    """
    Calculate the gradient of the stretching energy with respect to the coordinates.

    Args:
    - xk (float): x coordinate of the current point
    - yk (float): y coordinate of the current point
    - xkp1 (float): x coordinate of the next point
    - ykp1 (float): y coordinate of the next point
    - l_k (float): reference length
    - EA (float): elastic modulus

    Returns:
    - F (np.array): Gradient array
    """
    F = np.zeros(4)
    F[0] = -(1.0 - np.sqrt((xkp1 - xk)**2.0 + (ykp1 - yk)**2.0) / l_k) * ((xkp1 - xk)**2.0 + (ykp1 - yk)**2.0)**(-0.5) / l_k * (-2.0 * xkp1 + 2.0 * xk)
    F[1] = -(0.1e1 - np.sqrt((xkp1 - xk) ** 2 + (ykp1 - yk) ** 2) / l_k) * ((xkp1 - xk) ** 2 + (ykp1 - yk) ** 2) ** (-0.1e1 / 0.2e1) / l_k * (-0.2e1 * ykp1 + 0.2e1 * yk)
    F[2] = -(0.1e1 - np.sqrt((xkp1 - xk) ** 2 + (ykp1 - yk) ** 2) / l_k) * ((xkp1 - xk) ** 2 + (ykp1 - yk) ** 2) ** (-0.1e1 / 0.2e1) / l_k * (0.2e1 * xkp1 - 0.2e1 * xk)
    F[3] = -(0.1e1 - np.sqrt((xkp1 - xk) ** 2 + (ykp1 - yk) ** 2) / l_k) * ((xkp1 - xk) ** 2 + (ykp1 - yk) ** 2) ** (-0.1e1 / 0.2e1) / l_k * (0.2e1 * ykp1 - 0.2e1 * yk)

    F = 0.5 * EA * l_k * F  # Scale by EA and l_k

    return F

def hessEs(xk, yk, xkp1, ykp1, l_k, EA):
    """
    This function returns the 4x4 Hessian of the stretching energy E_k^s with
    respect to x_k, y_k, x_{k+1}, and y_{k+1}.
    """
    J = np.zeros((4, 4))  # Initialize the Hessian matrix
    J11 = (1 / ((xkp1 - xk) ** 2 + (ykp1 - yk) ** 2) / l_k ** 2 * (-2 * xkp1 + 2 * xk) ** 2) / 0.2e1 + (0.1e1 - np.sqrt(((xkp1 - xk) ** 2 + (ykp1 - yk) ** 2)) / l_k) * (((xkp1 - xk) ** 2 + (ykp1 - yk) ** 2) ** (-0.3e1 / 0.2e1)) / l_k * ((-2 * xkp1 + 2 * xk) ** 2) / 0.2e1 - 0.2e1 * (0.1e1 - np.sqrt(((xkp1 - xk) ** 2 + (ykp1 - yk) ** 2)) / l_k) * (((xkp1 - xk) ** 2 + (ykp1 - yk) ** 2) ** (-0.1e1 / 0.2e1)) / l_k
    J12 = (1 / ((xkp1 - xk) ** 2 + (ykp1 - yk) ** 2) / l_k ** 2 * (-2 * ykp1 + 2 * yk) * (-2 * xkp1 + 2 * xk)) / 0.2e1 + (0.1e1 - np.sqrt(((xkp1 - xk) ** 2 + (ykp1 - yk) ** 2)) / l_k) * (((xkp1 - xk) ** 2 + (ykp1 - yk) ** 2) ** (-0.3e1 / 0.2e1)) / l_k * (-2 * xkp1 + 2 * xk) * (-2 * ykp1 + 2 * yk) / 0.2e1
    J13 = (1 / ((xkp1 - xk) ** 2 + (ykp1 - yk) ** 2) / l_k ** 2 * (2 * xkp1 - 2 * xk) * (-2 * xkp1 + 2 * xk)) / 0.2e1 + (0.1e1 - np.sqrt(((xkp1 - xk) ** 2 + (ykp1 - yk) ** 2)) / l_k) * (((xkp1 - xk) ** 2 + (ykp1 - yk) ** 2) ** (-0.3e1 / 0.2e1)) / l_k * (-2 * xkp1 + 2 * xk) * (2 * xkp1 - 2 * xk) / 0.2e1 + 0.2e1 * (0.1e1 - np.sqrt(((xkp1 - xk) ** 2 + (ykp1 - yk) ** 2)) / l_k) * (((xkp1 - xk) ** 2 + (ykp1 - yk) ** 2) ** (-0.1e1 / 0.2e1)) / l_k
    J14 = (1 / ((xkp1 - xk) ** 2 + (ykp1 - yk) ** 2) / l_k ** 2 * (2 * ykp1 - 2 * yk) * (-2 * xkp1 + 2 * xk)) / 0.2e1 + (0.1e1 - np.sqrt(((xkp1 - xk) ** 2 + (ykp1 - yk) ** 2)) / l_k) * (((xkp1 - xk) ** 2 + (ykp1 - yk) ** 2) ** (-0.3e1 / 0.2e1)) / l_k * (-2 * xkp1 + 2 * xk) * (2 * ykp1 - 2 * yk) / 0.2e1
    J22 = (1 / ((xkp1 - xk) ** 2 + (ykp1 - yk) ** 2) / l_k ** 2 * (-2 * ykp1 + 2 * yk) ** 2) / 0.2e1 + (0.1e1 - np.sqrt(((xkp1 - xk) ** 2 + (ykp1 - yk) ** 2)) / l_k) * (((xkp1 - xk) ** 2 + (ykp1 - yk) ** 2) ** (-0.3e1 / 0.2e1)) / l_k * ((-2 * ykp1 + 2 * yk) ** 2) / 0.2e1 - 0.2e1 * (0.1e1 - np.sqrt(((xkp1 - xk) ** 2 + (ykp1 - yk) ** 2)) / l_k) * (((xkp1 - xk) ** 2 + (ykp1 - yk) ** 2) ** (-0.1e1 / 0.2e1)) / l_k
    J23 = (1 / ((xkp1 - xk) ** 2 + (ykp1 - yk) ** 2) / l_k ** 2 * (2 * xkp1 - 2 * xk) * (-2 * ykp1 + 2 * yk)) / 0.2e1 + (0.1e1 - np.sqrt(((xkp1 - xk) ** 2 + (ykp1 - yk) ** 2)) / l_k) * (((xkp1 - xk) ** 2 + (ykp1 - yk) ** 2) ** (-0.3e1 / 0.2e1)) / l_k * (-2 * ykp1 + 2 * yk) * (2 * xkp1 - 2 * xk) / 0.2e1
    J24 = (1 / ((xkp1 - xk) ** 2 + (ykp1 - yk) ** 2) / l_k ** 2 * (2 * ykp1 - 2 * yk) * (-2 * ykp1 + 2 * yk)) / 0.2e1 + (0.1e1 - np.sqrt(((xkp1 - xk) ** 2 + (ykp1 - yk) ** 2)) / l_k) * (((xkp1 - xk) ** 2 + (ykp1 - yk) ** 2) ** (-0.3e1 / 0.2e1)) / l_k * (-2 * ykp1 + 2 * yk) * (2 * ykp1 - 2 * yk) / 0.2e1 + 0.2e1 * (0.1e1 - np.sqrt(((xkp1 - xk) ** 2 + (ykp1 - yk) ** 2)) / l_k) * (((xkp1 - xk) ** 2 + (ykp1 - yk) ** 2) ** (-0.1e1 / 0.2e1)) / l_k
    J33 = (1 / ((xkp1 - xk) ** 2 + (ykp1 - yk) ** 2) / l_k ** 2 * (2 * xkp1 - 2 * xk) ** 2) / 0.2e1 + (0.1e1 - np.sqrt(((xkp1 - xk) ** 2 + (ykp1 - yk) ** 2)) / l_k) * (((xkp1 - xk) ** 2 + (ykp1 - yk) ** 2) ** (-0.3e1 / 0.2e1)) / l_k * ((2 * xkp1 - 2 * xk) ** 2) / 0.2e1 - 0.2e1 * (0.1e1 - np.sqrt(((xkp1 - xk) ** 2 + (ykp1 - yk) ** 2)) / l_k) * (((xkp1 - xk) ** 2 + (ykp1 - yk) ** 2) ** (-0.1e1 / 0.2e1)) / l_k
    J34 = (1 / ((xkp1 - xk) ** 2 + (ykp1 - yk) ** 2) / l_k ** 2 * (2 * ykp1 - 2 * yk) * (2 * xkp1 - 2 * xk)) / 0.2e1 + (0.1e1 - np.sqrt(((xkp1 - xk) ** 2 + (ykp1 - yk) ** 2)) / l_k) * (((xkp1 - xk) ** 2 + (ykp1 - yk) ** 2) ** (-0.3e1 / 0.2e1)) / l_k * (2 * xkp1 - 2 * xk) * (2 * ykp1 - 2 * yk) / 0.2e1
    J44 = (1 / ((xkp1 - xk) ** 2 + (ykp1 - yk) ** 2) / l_k ** 2 * (2 * ykp1 - 2 * yk) ** 2) / 0.2e1 + (0.1e1 - np.sqrt(((xkp1 - xk) ** 2 + (ykp1 - yk) ** 2)) / l_k) * (((xkp1 - xk) ** 2 + (ykp1 - yk) ** 2) ** (-0.3e1 / 0.2e1)) / l_k * ((2 * ykp1 - 2 * yk) ** 2) / 0.2e1 - 0.2e1 * (0.1e1 - np.sqrt(((xkp1 - xk) ** 2 + (ykp1 - yk) ** 2)) / l_k) * (((xkp1 - xk) ** 2 + (ykp1 - yk) ** 2) ** (-0.1e1 / 0.2e1)) / l_k

    J = np.array([[J11, J12, J13, J14],
                   [J12, J22, J23, J24],
                   [J13, J23, J33, J34],
                   [J14, J24, J34, J44]])

    J *= 0.5 * EA * l_k

    return J

"""# Functions to create elastic force vector and its Hessian"""

def getFs(q, EA, deltaL):
  # q - DOF vector of size N
  # EA - stretching stiffness
  # deltaL - undeformed reference length (assume to be a scalar for this simple example)
  # Output:
  # Fs - a vector (negative gradient of elastic stretching force)
  # Js - a matrix (negative hessian of elastic stretching force)

  ndof = q.size # Number of DOFs
  N = ndof // 2 # Number of nodes

  Fs = np.zeros(ndof) # stretching force
  Js = np.zeros((ndof, ndof))

  for k in range(0, N-1):
      # May need to modify if network of beams
      # k-th stretching spring (USE A LOOP for the general case
      xkm1 = q[2*k] # x coordinate of the first node
      ykm1 = q[2*k+1] # y coordinate of the first node
      xk = q[2*k+2] # x coordinate of the second node
      yk = q[2*k+3] # y coordinate of the second node
      ind = np.arange(2*k, 2*k+4) # 0, 1, 2, 3 for k = 0
      gradEnergy = gradEs(xkm1, ykm1, xk, yk, deltaL, EA)
      hessEnergy = hessEs(xkm1, ykm1, xk, yk, deltaL, EA)

      Fs[ind] -= gradEnergy # force = - gradient of energy. Fs is the stretching force
      Js[np.ix_(ind, ind)] -= hessEnergy # index vector: 0:4

  return Fs, Js

def getFb(q, EI, deltaL):
  # q - DOF vector of size N
  # EI - bending stiffness
  # deltaL - undeformed Voronoi length (assume to be a scalar for this simple example)
  # Output:
  # Fb - a vector (negative gradient of elastic stretching force)
  # Jb - a matrix (negative hessian of elastic stretching force)

  ndof = q.size # Number of DOFs
  N = ndof // 2 # Number of nodes

  Fb = np.zeros(ndof) # bending force
  Jb = np.zeros((ndof, ndof))

  # First bending spring (USE A LOOP for the general case)
  for k in range(1, N-1):
    xkm1 = q[2*k-2] # x coordinate of the first node
    ykm1 = q[2*k-1] # y coordinate of the first node
    xk = q[2*k] # x coordinate of the second node
    yk = q[2*k+1] # y coordinate of the second node
    xkp1 = q[2*k+2] # x coordinate of the third node
    ykp1 = q[2*k+3] # y coordinate of the third node
    ind = np.arange(2*k-2, 2*k+4)
    gradEnergy = gradEb(xkm1, ykm1, xk, yk, xkp1, ykp1, 0, deltaL, EI)
    hessEnergy = hessEb(xkm1, ykm1, xk, yk, xkp1, ykp1, 0, deltaL, EI)

    Fb[ind] -= gradEnergy # force = - gradient of energy. Fb is the stretching force
    Jb[np.ix_(ind, ind)] -= hessEnergy # index vector: 0:6

  return Fb, Jb

"""# Objective Function or Integrator

Given the old position and the old velocity, find out th new position and the new velocity
"""

def objfun(q_old, u_old, dt, tol, maximum_iter,
           m, mMat, # inertia
           EI, EA, # elastic stiffness
           W, C, # external force
           deltaL,
           free_index):

  q_new = q_old.copy() # Guess solution

  # Newton Raphson
  iter_count = 0 # number of iterations
  error = tol * 10 # error
  flag = 1 # if flag = 1, it is a good solution

  while error > tol:
    # Inertia
    F_inertia = m/dt * ((q_new - q_old) / dt - u_old)
    J_inertia = mMat / dt ** 2

    # Elastic forces: Stretching and Bending
    Fs, Js = getFs(q_new, EA, deltaL)
    Fb, Jb = getFb(q_new, EI, deltaL)
    F_elastic = Fs + Fb
    J_elastic = Js + Jb

    # External forces
    # Viscous force
    Fv = - C @ ( q_new - q_old ) / dt
    Jv = - C / dt

    # Equations of motion
    f = F_inertia - F_elastic - Fv - W
    J = J_inertia - J_elastic - Jv

    f_free = f[free_index]
    J_free = J[np.ix_(free_index, free_index)]

    # Newton's update (all DOFs are FREE)
    dq_free = np.linalg.solve(J_free, f_free)
    q_new[free_index] = q_new[free_index] - dq_free

    # Get the error
    error = np.linalg.norm(f_free)

    # Update the iteration number
    iter_count += 1
    if iter_count > maximum_iter:
      flag = -1 # Return with an error signal
      print("Maximum number of iterations reached.")
      return q_new, flag

    # u_new = (q_new - q_old) / dt # Velocity
  return q_new, flag

"""# apply_dirichlet_bc Function
Enforces boundary conditions on end node N-1
"""

def apply_dirichlet_bc(q, x_c, y_c, theta_c, deltaL, nv):
    end_node = nv - 1
    end_node_prev = nv - 2

    # Compute positions
    x_N = x_c
    y_N = y_c
    x_N_1 = x_c - deltaL * np.cos(theta_c)
    y_N_1 = y_c - deltaL * np.sin(theta_c)

    # Overwrite DOFs
    q[2 * end_node] = x_N
    q[2 * end_node + 1] = y_N
    q[2 * end_node_prev] = x_N_1
    q[2 * end_node_prev + 1] = y_N_1
    return q

"""# setup_simulation_parameters()
Function to define beam parameters including external forces (gravity) and damping
"""

def setup_simulation_parameters():
    params = {}

    # Simulation & Beam Parameters
    nv = 19                                # Number of nodes
    ndof = 2 * nv                          # Degrees of freedom
    L = 1.0                                # Beam length (m)
    deltaL = L / (nv - 1)                  # Segment length
    totalTime = 1.0                        # Total simulation time (s)
    dt = 0.001                             # Time step size (s)
    Nsteps = int(totalTime / dt)

    # Material Properties
    rho = 2700                      # Density (kg/m^3)
    r0, R = 0.011, 0.013            # Inner & Outer radius (m)
    Y = 70e9                              # Young's modulus (Pa)

    # Cross-section and stiffness
    A = np.pi * (R**2 - r0**2)            # Cross-sectional area (m^2)
    I = (np.pi / 4) * (R**4 - r0**4)      # Moment of inertia (m^4)
    EA = Y * A
    EI = Y * I

    # Mass Matrix
    m_node = A * L * rho / (nv - 1)  # Mass per node (uniform)
    m = np.full(2 * nv, m_node)                    # Mass vector
    mMat = np.diag(m)                              # Diagonal mass matrix

    # Initial Geometry
    nodes = np.zeros((nv, 2))
    for c in range(nv):
        nodes[c, 0] = c * deltaL  # Uniform x-positions
        nodes[c, 1] = 0.0         # Flat y=0 initially

    # External Forces
    g = 9.81  # m/s^2
    W = np.zeros(2 * nv)
    W[1::2] = -m_node * g  # Apply to all odd indices (y-DOFs)

    # Damping Matrix
    C = np.zeros((2 * nv, 2 * nv))          # No damping

    q0 = np.zeros(ndof)
    q0[0::2] = nodes[:, 0]
    q0[1::2] = nodes[:, 1]
    u0 = np.zeros(ndof)

    end_node = nv - 1
    end_node_m1 = nv - 2
    all_DOFs = np.arange(ndof)
    fixed_index = np.array([0, 1, 2*end_node+1, 2*end_node, 2*end_node_m1 + 1, 2*end_node_m1])
    free_index = np.setdiff1d(all_DOFs, fixed_index)

    # Store everything needed
    params.update({
        'nv': nv,
        'ndof': ndof,
        'L': L,
        'deltaL': deltaL,
        'dt': dt,
        'totalTime': totalTime,
        'Nsteps': Nsteps,
        'q0': q0,
        'u0': u0,
        'A': A,
        'I': I,
        'EA': EA,
        'EI': EI,
        'm': m,
        'mMat': mMat,
        'W': W,
        'C': C,
        'tol': EI / L**2 * 1e-3,
        'maximum_iter': 1000,
        'free_index': free_index,
        'objfun': objfun,  # pass in your actual function
    })

    return params

"""# simulate_pi_controller()
Main loop that simulates beam shape over time and updates control inputs for trajectory tracking
"""

def simulate_pi_controller(objfun, apply_dirichlet_bc, params):
    # --- Unpack parameters ---
    nv         = params['nv']
    ndof       = params['ndof']
    L          = params['L']
    deltaL     = params['deltaL']
    dt         = params['dt']
    totalTime  = params['totalTime']
    Nsteps     = params['Nsteps']
    tol        = params['tol']
    max_iter   = params['maximum_iter']
    m          = params['m']
    mMat       = params['mMat']
    EI         = params['EI']
    EA         = params['EA']
    W          = params['W']
    C          = params['C']
    free_index = params['free_index']
    q0         = params['q0'].copy()
    u0         = params['u0'].copy()

    # --- Geometry indices ---
    midNode      = nv // 2
    end_node     = nv - 1
    end_node_m1  = nv - 2

    # --- PI Gains (XY and θ) ---
    Kp = np.array([0.4, 0.4, 1.0])
    Ki = np.array([5.0, 5.0, 1.0])
    Kd = np.array([0.0, 0.0, 0])
    alpha = 0.5  # derivative smoothing

    # --- Initial Control States ---
    x_c = L
    y_c = 0
    theta_c = 0
    ctime = 0.0

    # --- PID Memory terms ---
    error_prev       = np.zeros(3)
    error_deriv_prev = np.zeros(3)
    error_sum        = np.zeros(3)

    # --- Logging arrays ---
    xyc_traj      = np.zeros((Nsteps, 2))  # tip node
    xyc_m1_traj   = np.zeros((Nsteps, 2))  # tip-1 node
    mid_star_traj = np.zeros((Nsteps, 2))
    mid_traj      = np.zeros((Nsteps, 2))
    theta_val     = np.zeros(Nsteps)
    theta_star_log = np.zeros(Nsteps)
    error_log     = np.zeros((Nsteps, 3))
    control_log   = np.zeros((Nsteps, 3))

    # --- Main loop ---
    for t in range(1, Nsteps):
        # Step simulation forward
        q_new, err = objfun(q0, u0, dt, tol, max_iter, m, mMat, EI, EA, W, C, deltaL, free_index)
        if err < 0:
            print(f"Did not converge at step {t}")
            break

        q_new = apply_dirichlet_bc(q_new, x_c, y_c, theta_c, deltaL, nv)
        u_new = (q_new - q0) / dt
        ctime += dt

        # --- Record node positions ---
        xyc_traj[t] = q_new[2*end_node:2*end_node+2]
        xyc_m1_traj[t] = q_new[2*end_node_m1:2*end_node_m1+2]
        mid_traj[t] = q_new[2*midNode:2*midNode+2]

        # --- Desired middle node trajectory ---
        mid_star_traj[t] = np.array([
            (L / 2) * np.cos(np.pi * ctime / 2000),
            -(L / 2) * np.sin(np.pi * ctime / 2000)
        ])

        # --- Desired orientation θ* (0 → -π/8 smooth sweep) ---
        theta_star = np.linspace(0, np.pi / 8, Nsteps)
        theta_star_log[t] = theta_star[t]
        theta_val[t] = theta_c  # log current actual θ

        # --- Compute control errors ---
        error = np.array([
            mid_traj[t, 0] - mid_star_traj[t, 0],
            mid_traj[t, 1] - mid_star_traj[t, 1],
            theta_c - theta_star[t]
        ])

        # --- PI controller ---
        error_sum += error * dt
        error_deriv = alpha * error_deriv_prev + (1 - alpha) * ((error - error_prev) / dt)
        delta_u = Kp * error + Ki * error_sum  - Kd * error_deriv
        delta_u = np.clip(delta_u, [-0.003, -0.003, -0.02], [0.003, 0.003, 0.02])

        # --- Update control states ---
        x_c     += -delta_u[0]
        y_c     += -delta_u[1]
        theta_c += -delta_u[2]

        # --- Update logs ---
        error_prev       = error.copy()
        error_deriv_prev = error_deriv.copy()
        error_log[t]     = error
        control_log[t]   = delta_u

        # --- Advance simulation state ---
        q0 = q_new.copy()
        u0 = u_new.copy()

        # --- Progress printout ---
        if t % 100 == 0:
            print(f"t={ctime:.3f}s | err=({error[0]:.4e}, {error[1]:.4e}, {error[2]:.4e}) | θc={theta_c:.4f}")

        if t % 200 == 0:
            plot_beam(q_new, ctime)

        if t == 999:
            plot_beam(q_new, ctime)

    # --- Return all logged data ---
    return {
        'xyc_traj': xyc_traj,
        'xyc_m1_traj': xyc_m1_traj,
        'mid_traj': mid_traj,
        'mid_star_traj': mid_star_traj,
        'theta_val': theta_val,
        'theta_star': theta_star_log,
        'error_log': error_log,
        'control_log': control_log
    }

"""# plot functions"""

def plot_beam(q, ctime):
    x_arr = q[::2]
    y_arr = q[1::2]
    plt.figure()
    plt.plot(x_arr, y_arr, 'ko-', markersize=4, label='Beam Nodes')
    plt.title(f't = {ctime:.3f}s')
    plt.xlabel('x'); plt.ylabel('y')
    plt.axis('equal'); plt.legend(); plt.grid(True); plt.show()

def plot_results(results, params):
    t_vals = np.linspace(0, params['totalTime'], params['Nsteps'])

    mid_star_traj = results['mid_star_traj']
    mid_traj      = results['mid_traj']
    theta_val     = results['theta_val']
    theta_star    = results['theta_star']
    error_log     = results['error_log']
    control_log   = results['control_log']

    # --- Mid-node Trajectory (XY Plot) ---
    plt.figure(figsize=(6, 5))
    plt.plot(mid_star_traj[1:, 0], mid_star_traj[1:, 1], 'r--', label='Desired Path')
    plt.plot(mid_traj[1:, 0], mid_traj[1:, 1], 'k-', label='Actual Path')
    plt.xlabel('X Position (m)')
    plt.ylabel('Y Position (m)')
    plt.title('Middle Node Trajectory')
    plt.legend()
    plt.axis('equal')
    plt.grid(True)
    plt.show()

    # --- X and Y vs Time ---
    fig, axs = plt.subplots(2, 1, figsize=(8, 6), sharex=True)
    axs[0].plot(t_vals[1:], mid_star_traj[1:, 0], 'r--', label='X*')
    axs[0].plot(t_vals[1:], mid_traj[1:, 0], 'k-', label='X')
    axs[0].set_ylabel("X (m)")
    axs[0].grid(True)
    axs[0].legend()

    axs[1].plot(t_vals, mid_star_traj[:, 1], 'r--', label='Y*')
    axs[1].plot(t_vals, mid_traj[:, 1], 'k-', label='Y')
    axs[1].set_xlabel("Time (s)")
    axs[1].set_ylabel("Y (m)")
    axs[1].grid(True)
    axs[1].legend()

    fig.suptitle("Middle Node Position vs. Time")
    plt.show()

    # --- Theta vs Time ---
    plt.figure(figsize=(7, 4))
    plt.plot(t_vals, theta_star, 'r--', label='θ* (desired)')
    plt.plot(t_vals, theta_val,  'k-', label='θc (actual)')
    plt.xlabel("Time (s)")
    plt.ylabel("θ (radians)")
    plt.title("Orientation θc vs Time")
    plt.legend()
    plt.grid(True)
    plt.show()

    # --- Control Inputs ---
    plt.figure(figsize=(8, 5))
    plt.plot(t_vals, control_log[:, 0], label='Δx_c')
    plt.plot(t_vals, control_log[:, 1], label='Δy_c')
    plt.plot(t_vals, control_log[:, 2], label='Δθ_c')
    plt.xlabel("Time (s)")
    plt.ylabel("Control Input")
    plt.title("Control Inputs Over Time")
    plt.legend()
    plt.grid(True)
    plt.show()

    # --- Error (x, y, θ) ---
    fig, axs = plt.subplots(3, 1, figsize=(8, 6), sharex=True)
    axs[0].plot(t_vals, error_log[:, 0])
    axs[0].set_ylabel("X Error (m)")
    axs[0].grid(True)

    axs[1].plot(t_vals, error_log[:, 1])
    axs[1].set_ylabel("Y Error (m)")
    axs[1].grid(True)

    axs[2].plot(t_vals, error_log[:, 2])
    axs[2].set_ylabel("θ Error (rad)")
    axs[2].set_xlabel("Time (s)")
    axs[2].grid(True)

    fig.suptitle("Tracking Error Over Time")
    plt.show()

"""# Main

**Time stepping loop**
"""

params = setup_simulation_parameters()
results = simulate_pi_controller(objfun, apply_dirichlet_bc, params)
plot_results(results, params)