# -*- coding: utf-8 -*-
"""Homework5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q7uN9b8qWA8HJPw7Nzs2EVRvxUyr20AC

# Discrete Elastic Shells: Simple Example with Four Nodes
Copyright M. Khalid Jawed (khalidjm@seas.ucla.edu). License: CC BY-NC
You should use this code at your own risk.

#Load Libraries
"""

# from IPython.display import clear_output
import numpy as np
import matplotlib.pyplot as plt

"""#Miscellaneous Functions: signedAngle, rotateAxisAngle, parallel_transport, crossMat"""

def signedAngle(u = None,v = None,n = None):
    # This function calculates the signed angle between two vectors, "u" and "v",
    # using an optional axis vector "n" to determine the direction of the angle.
    #
    # Parameters:
    #   u: numpy array-like, shape (3,), the first vector.
    #   v: numpy array-like, shape (3,), the second vector.
    #   n: numpy array-like, shape (3,), the axis vector that defines the plane
    #      in which the angle is measured. It determines the sign of the angle.
    #
    # Returns:
    #   angle: float, the signed angle (in radians) from vector "u" to vector "v".
    #          The angle is positive if the rotation from "u" to "v" follows
    #          the right-hand rule with respect to the axis "n", and negative otherwise.
    #
    # The function works by:
    # 1. Computing the cross product "w" of "u" and "v" to find the vector orthogonal
    #    to both "u" and "v".
    # 2. Calculating the angle between "u" and "v" using the arctan2 function, which
    #    returns the angle based on the norm of "w" (magnitude of the cross product)
    #    and the dot product of "u" and "v".
    # 3. Using the dot product of "n" and "w" to determine the sign of the angle.
    #    If this dot product is negative, the angle is adjusted to be negative.
    #
    # Example:
    #   signedAngle(np.array([1, 0, 0]), np.array([0, 1, 0]), np.array([0, 0, 1]))
    #   This would return a positive angle (π/2 radians), as the rotation
    #   from the x-axis to the y-axis is counterclockwise when viewed along the z-axis.
    w = np.cross(u,v)
    angle = np.arctan2( np.linalg.norm(w), np.dot(u,v) )
    if (np.dot(n,w) < 0):
        angle = - angle

    return angle

def mmt(matrix):
    return matrix + matrix.T

"""# Hinge angle, its gradient, and Hessian"""

#          x2
#          /\
#         /  \
#      e1/    \e3
#       /  t0  \
#      /        \
#     /    e0    \
#   x0------------x1
#     \          /
#      \   t1   /
#       \      /
#      e2\    /e4
#         \  /
#          \/
#          x3
#
#  Edge orientation: e0,e1,e2 point away from x0
#                       e3,e4 point away from x1

def getTheta(x0, x1 = None, x2 = None, x3 = None):

    if np.size(x0) == 12:  # Allow another type of input where x0 contains all the info
      x1 = x0[3:6]
      x2 = x0[6:9]
      x3 = x0[9:12]
      x0 = x0[0:3]

    m_e0 = x1 - x0
    m_e1 = x2 - x0
    m_e2 = x3 - x0

    n0 = np.cross(m_e0, m_e1)
    n1 = np.cross(m_e2, m_e0)

    # Calculate the signed angle using the provided function
    theta = signedAngle(n0, n1, m_e0)

    return theta

# In the original code, there are probaly TWO sign errors in the expressions for m_h3 and m_h4.
# [Original code: % https://github.com/shift09/plates-shells/blob/master/src/bending.cpp]
# I indicated those two corrections by writing the word "CORRECTION" next
# to them.

def gradTheta(x0, x1 = None, x2 = None, x3 = None):

    if np.size(x0) == 12:  # Allow another type of input where x0 contains all the info
      x1 = x0[3:6]
      x2 = x0[6:9]
      x3 = x0[9:12]
      x0 = x0[0:3]

    m_e0 = x1 - x0
    m_e1 = x2 - x0
    m_e2 = x3 - x0
    m_e3 = x2 - x1
    m_e4 = x3 - x1

    m_cosA1 = np.dot(m_e0, m_e1) / (np.linalg.norm(m_e0) * np.linalg.norm(m_e1))
    m_cosA2 = np.dot(m_e0, m_e2) / (np.linalg.norm(m_e0) * np.linalg.norm(m_e2))
    m_cosA3 = -np.dot(m_e0, m_e3) / (np.linalg.norm(m_e0) * np.linalg.norm(m_e3))
    m_cosA4 = -np.dot(m_e0, m_e4) / (np.linalg.norm(m_e0) * np.linalg.norm(m_e4))

    m_sinA1 = np.linalg.norm(np.cross(m_e0, m_e1)) / (np.linalg.norm(m_e0) * np.linalg.norm(m_e1))
    m_sinA2 = np.linalg.norm(np.cross(m_e0, m_e2)) / (np.linalg.norm(m_e0) * np.linalg.norm(m_e2))
    m_sinA3 = -np.linalg.norm(np.cross(m_e0, m_e3)) / (np.linalg.norm(m_e0) * np.linalg.norm(m_e3))
    m_sinA4 = -np.linalg.norm(np.cross(m_e0, m_e4)) / (np.linalg.norm(m_e0) * np.linalg.norm(m_e4))

    m_nn1 = np.cross(m_e0, m_e3)
    m_nn1 = m_nn1 / np.linalg.norm(m_nn1)
    m_nn2 = -np.cross(m_e0, m_e4)
    m_nn2 = m_nn2 / np.linalg.norm(m_nn2)

    m_h1 = np.linalg.norm(m_e0) * m_sinA1
    m_h2 = np.linalg.norm(m_e0) * m_sinA2
    m_h3 = -np.linalg.norm(m_e0) * m_sinA3  # CORRECTION
    m_h4 = -np.linalg.norm(m_e0) * m_sinA4  # CORRECTION
    m_h01 = np.linalg.norm(m_e1) * m_sinA1
    m_h02 = np.linalg.norm(m_e2) * m_sinA2

    # Initialize the gradient
    gradTheta = np.zeros(12)

    gradTheta[0:3] = m_cosA3 * m_nn1 / m_h3 + m_cosA4 * m_nn2 / m_h4
    gradTheta[3:6] = m_cosA1 * m_nn1 / m_h1 + m_cosA2 * m_nn2 / m_h2
    gradTheta[6:9] = -m_nn1 / m_h01
    gradTheta[9:12] = -m_nn2 / m_h02

    return gradTheta

def hessTheta(x0, x1 = None, x2 = None, x3 = None):

    if np.size(x0) == 12:  # Allow another type of input where x0 contains all the info
      x1 = x0[3:6]
      x2 = x0[6:9]
      x3 = x0[9:12]
      x0 = x0[0:3]

    m_e0 = x1 - x0
    m_e1 = x2 - x0
    m_e2 = x3 - x0
    m_e3 = x2 - x1
    m_e4 = x3 - x1

    m_cosA1 = np.dot(m_e0, m_e1) / (np.linalg.norm(m_e0) * np.linalg.norm(m_e1))
    m_cosA2 = np.dot(m_e0, m_e2) / (np.linalg.norm(m_e0) * np.linalg.norm(m_e2))
    m_cosA3 = -np.dot(m_e0, m_e3) / (np.linalg.norm(m_e0) * np.linalg.norm(m_e3))
    m_cosA4 = -np.dot(m_e0, m_e4) / (np.linalg.norm(m_e0) * np.linalg.norm(m_e4))

    m_sinA1 = np.linalg.norm(np.cross(m_e0, m_e1)) / (np.linalg.norm(m_e0) * np.linalg.norm(m_e1))
    m_sinA2 = np.linalg.norm(np.cross(m_e0, m_e2)) / (np.linalg.norm(m_e0) * np.linalg.norm(m_e2))
    m_sinA3 = -np.linalg.norm(np.cross(m_e0, m_e3)) / (np.linalg.norm(m_e0) * np.linalg.norm(m_e3))
    m_sinA4 = -np.linalg.norm(np.cross(m_e0, m_e4)) / (np.linalg.norm(m_e0) * np.linalg.norm(m_e4))

    m_nn1 = np.cross(m_e0, m_e3)
    m_nn1 /= np.linalg.norm(m_nn1)
    m_nn2 = -np.cross(m_e0, m_e4)
    m_nn2 /= np.linalg.norm(m_nn2)

    m_h1 = np.linalg.norm(m_e0) * m_sinA1
    m_h2 = np.linalg.norm(m_e0) * m_sinA2
    m_h3 = -np.linalg.norm(m_e0) * m_sinA3
    m_h4 = -np.linalg.norm(m_e0) * m_sinA4
    m_h01 = np.linalg.norm(m_e1) * m_sinA1
    m_h02 = np.linalg.norm(m_e2) * m_sinA2

    # Gradient of Theta (as an intermediate step)
    grad_theta = np.zeros((12, 1))
    grad_theta[0:3] = (m_cosA3 * m_nn1 / m_h3 + m_cosA4 * m_nn2 / m_h4).reshape(-1, 1)
    grad_theta[3:6] = (m_cosA1 * m_nn1 / m_h1 + m_cosA2 * m_nn2 / m_h2).reshape(-1, 1)
    grad_theta[6:9] = (-m_nn1 / m_h01).reshape(-1, 1)
    grad_theta[9:12] = (-m_nn2 / m_h02).reshape(-1, 1)

    # Intermediate matrices for Hessian
    m_m1 = np.cross(m_nn1, m_e1) / np.linalg.norm(m_e1)
    m_m2 = -np.cross(m_nn2, m_e2) / np.linalg.norm(m_e2)
    m_m3 = -np.cross(m_nn1, m_e3) / np.linalg.norm(m_e3)
    m_m4 = np.cross(m_nn2, m_e4) / np.linalg.norm(m_e4)
    m_m01 = -np.cross(m_nn1, m_e0) / np.linalg.norm(m_e0)
    m_m02 = np.cross(m_nn2, m_e0) / np.linalg.norm(m_e0)

    # Hessian matrix components
    M331 = m_cosA3 / (m_h3 ** 2) * np.outer(m_m3, m_nn1)
    M311 = m_cosA3 / (m_h3 * m_h1) * np.outer(m_m1, m_nn1)
    M131 = m_cosA1 / (m_h1 * m_h3) * np.outer(m_m3, m_nn1)
    M3011 = m_cosA3 / (m_h3 * m_h01) * np.outer(m_m01, m_nn1)
    M111 = m_cosA1 / (m_h1 ** 2) * np.outer(m_m1, m_nn1)
    M1011 = m_cosA1 / (m_h1 * m_h01) * np.outer(m_m01, m_nn1)

    M442 = m_cosA4 / (m_h4 ** 2) * np.outer(m_m4, m_nn2)
    M422 = m_cosA4 / (m_h4 * m_h2) * np.outer(m_m2, m_nn2)
    M242 = m_cosA2 / (m_h2 * m_h4) * np.outer(m_m4, m_nn2)
    M4022 = m_cosA4 / (m_h4 * m_h02) * np.outer(m_m02, m_nn2)
    M222 = m_cosA2 / (m_h2 ** 2) * np.outer(m_m2, m_nn2)
    M2022 = m_cosA2 / (m_h2 * m_h02) * np.outer(m_m02, m_nn2)

    B1 = 1 / np.linalg.norm(m_e0) ** 2 * np.outer(m_nn1, m_m01)
    B2 = 1 / np.linalg.norm(m_e0) ** 2 * np.outer(m_nn2, m_m02)

    N13 = 1 / (m_h01 * m_h3) * np.outer(m_nn1, m_m3)
    N24 = 1 / (m_h02 * m_h4) * np.outer(m_nn2, m_m4)
    N11 = 1 / (m_h01 * m_h1) * np.outer(m_nn1, m_m1)
    N22 = 1 / (m_h02 * m_h2) * np.outer(m_nn2, m_m2)
    N101 = 1 / (m_h01 ** 2) * np.outer(m_nn1, m_m01)
    N202 = 1 / (m_h02 ** 2) * np.outer(m_nn2, m_m02)

    # Initialize Hessian of Theta
    hess_theta = np.zeros((12, 12))

    hess_theta[0:3, 0:3] = mmt(M331) - B1 + mmt(M442) - B2
    hess_theta[0:3, 3:6] = M311 + M131.T + B1 + M422 + M242.T + B2
    hess_theta[0:3, 6:9] = M3011 - N13
    hess_theta[0:3, 9:12] = M4022 - N24
    hess_theta[3:6, 3:6] = mmt(M111) - B1 + mmt(M222) - B2
    hess_theta[3:6, 6:9] = M1011 - N11
    hess_theta[3:6, 9:12] = M2022 - N22
    hess_theta[6:9, 6:9] = -mmt(N101)
    hess_theta[9:12, 9:12] = -mmt(N202)

    # Make the Hessian symmetric
    hess_theta[3:6, 0:3] = hess_theta[0:3, 3:6].T
    hess_theta[6:9, 0:3] = hess_theta[0:3, 6:9].T
    hess_theta[9:12, 0:3] = hess_theta[0:3, 9:12].T
    hess_theta[6:9, 3:6] = hess_theta[3:6, 6:9].T
    hess_theta[9:12, 3:6] = hess_theta[3:6, 9:12].T

    return hess_theta

"""# Stretching energy for a shell, it's gradient, and Hessian"""

def gradEs_hessEs(node0 = None,node1 = None,l_k = None,EA = None):

# Inputs:
# node0: 1x3 vector - position of the first node
# node1: 1x3 vector - position of the last node

# l_k: reference length (undeformed) of the edge
# EA: scalar - stretching stiffness - Young's modulus times area

# Outputs:
# dF: 6x1  vector - gradient of the stretching energy between node0 and node 1.
# dJ: 6x6 vector - hessian of the stretching energy between node0 and node 1.

    ## Gradient of Es
    edge = node1 - node0

    edgeLen = np.linalg.norm(edge)
    tangent = edge / edgeLen
    epsX = edgeLen / l_k - 1
    dF_unit = EA * tangent * epsX
    dF = np.zeros((6))
    dF[0:3] = - dF_unit
    dF[3:6] = dF_unit

    ## Hessian of Es
    Id3 = np.eye(3)
    M = EA * ((1 / l_k - 1 / edgeLen) * Id3 + 1 / edgeLen * ( np.outer( edge, edge ) ) / edgeLen ** 2)

    dJ = np.zeros((6,6))
    dJ[0:3,0:3] = M
    dJ[3:6,3:6] = M
    dJ[0:3,3:6] = - M
    dJ[3:6,0:3] = - M
    return dF,dJ

"""# Bending energy for a shell, it's gradient, and Hessian"""

def getEb_Shell(x0, x1=None, x2=None, x3=None, theta_bar=0, kb=1.0):
    """
    Compute the bending energy for a shell.

    Returns:
    E (scalar): Bending energy.
    """
    # Allow another type of input where x0 contains all the information
    if np.size(x0) == 12:
        x1 = x0[3:6]
        x2 = x0[6:9]
        x3 = x0[9:12]
        x0 = x0[:3]

    # Compute theta, gradient, and Hessian
    theta = getTheta(x0, x1, x2, x3)  # Replace with your getTheta function in Python
    grad = gradTheta(x0, x1, x2, x3)  # Replace with your gradTheta function in Python

    # E = 0.5 * kb * (theta-thetaBar)^2
    E = 0.5 * kb * (theta - theta_bar) ** 2

    return E

def gradEb_hessEb_Shell(x0, x1=None, x2=None, x3=None, theta_bar=0, kb=1.0):
    """
    Compute the gradient and Hessian of the bending energy for a shell.

    Parameters:
    x0 (array): Can either be a 3-element array (single point) or a 12-element array.
    x1, x2, x3 (arrays): Optional, 3-element arrays specifying points.
    theta_bar (float): Reference angle.
    kb (float): Bending stiffness.

    Returns:
    dF (array): Gradient of the bending energy.
    dJ (array): Hessian of the bending energy.
    """
    # Allow another type of input where x0 contains all the information
    if np.size(x0) == 12:
        x1 = x0[3:6]
        x2 = x0[6:9]
        x3 = x0[9:12]
        x0 = x0[:3]

    # Compute theta, gradient, and Hessian
    theta = getTheta(x0, x1, x2, x3)  # Replace with your getTheta function in Python
    grad = gradTheta(x0, x1, x2, x3)  # Replace with your gradTheta function in Python

    # E = 0.5 * kb * (theta-thetaBar)^2
    # F = dE/dx = 2 * (theta-thetaBar) * gradTheta
    dF = 0.5 * kb * (2 * (theta - theta_bar) * grad)

    # E = 0.5 * kb * (theta-thetaBar)^2
    # F = 0.5 * kb * (2 (theta-thetaBar) d theta/dx)
    # J = dF/dx = 0.5 * kb * [ 2 (d theta / dx) transpose(d theta/dx) +
    #       2 (theta-thetaBar) (d^2 theta/ dx^2 ) ]
    hess = hessTheta(x0, x1, x2, x3)  # Replace with your hessTheta function in Python
    dJ = 0.5 * kb * (2 * np.outer(grad, grad) + 2 * (theta - theta_bar) * hess)

    return dF, dJ

"""#Plot the shell"""

# Function to set equal aspect ratio for 3D plots
def set_axes_equal(ax):
    """
    Set equal aspect ratio for a 3D plot in Matplotlib.
    This function adjusts the limits of the plot to make sure
    that the scale is equal along all three axes.
    """
    x_limits = ax.get_xlim3d()
    y_limits = ax.get_ylim3d()
    z_limits = ax.get_zlim3d()

    x_range = abs(x_limits[1] - x_limits[0])
    y_range = abs(y_limits[1] - y_limits[0])
    z_range = abs(z_limits[1] - z_limits[0])

    max_range = max(x_range, y_range, z_range)

    x_middle = np.mean(x_limits)
    y_middle = np.mean(y_limits)
    z_middle = np.mean(z_limits)

    ax.set_xlim3d([x_middle - max_range / 2, x_middle + max_range / 2])
    ax.set_ylim3d([y_middle - max_range / 2, y_middle + max_range / 2])
    ax.set_zlim3d([z_middle - max_range / 2, z_middle + max_range / 2])

# Plot the whole plate shell
def plotShell(q, ctime):
    """
    Plot the current configuration of the plate using the global 'edges'
    (stretching edges) as a wireframe. Clamped nodes in 'fixed_nodes'
    are highlighted in red.
    """
    # q is a flat DOF vector of length ndof = 3 * nv
    nodes = q.reshape((-1, 3))  # (nv, 3)

    fig = plt.figure(1)
    # clear_output(wait=True)
    # plt.clf()
    ax = fig.add_subplot(111, projection='3d')

    # Plot all stretching edges as black lines
    for (i, j) in edges:
        xi = nodes[i]
        xj = nodes[j]
        ax.plot(
            [xi[0], xj[0]],
            [xi[1], xj[1]],
            [xi[2], xj[2]],
            'k-'
        )

    # Plot all nodes as black points
    ax.scatter(nodes[:, 0], nodes[:, 1], nodes[:, 2], c='k', s=20)

    # Highlight clamped nodes (if fixed_nodes is defined)
    try:
        fn = fixed_nodes
    except NameError:
        fn = []

    for n in fn:
        x = nodes[n]
        ax.plot([x[0]], [x[1]], [x[2]], 'r^', markersize=8)

    ax.set_title(f't = {ctime:.2f} s')
    ax.set_xlabel('x')
    ax.set_ylabel('y')
    ax.set_zlabel('z')

    set_axes_equal(ax)
    plt.draw()
    plt.show()

"""# Objective function"""

def objfun(qOld, uOld, freeIndex, dt, tol, massVector, massMatrix,
           ks, refLen, edges,
           kb, thetaBar, hinges,
           Fg, visc):

  qNew = qOld.copy()
  ndof = len(qOld) # Number of DOFs

  iter = 0 # number of iteration
  error = 10 * tol
  # Newton Raphson
  while error > tol:

    # Bending force and jacobian
    Fb = np.zeros( ndof )
    Jb = np.zeros( (ndof,ndof) )
    # Loop over every "bending spring" or "hinge"
    for kHinge in range(hinges.shape[0]):
      node0 = hinges[kHinge, 0]
      node1 = hinges[kHinge, 1]
      node2 = hinges[kHinge, 2]
      node3 = hinges[kHinge, 3]
      x0 = qNew[ 3*node0: 3*node0 + 3]
      x1 = qNew[ 3*node1: 3*node1 + 3]
      x2 = qNew[ 3*node2: 3*node2 + 3]
      x3 = qNew[ 3*node3: 3*node3 + 3]
      ind = [3*node0, 3*node0 + 1, 3*node0 + 2,
             3*node1, 3*node1 + 1, 3*node1 + 2,
             3*node2, 3*node2 + 1, 3*node2 + 2,
             3*node3, 3*node3 + 1, 3*node3 + 2]
      dF, dJ = gradEb_hessEb_Shell(x0, x1, x2, x3, 0, kb)
      Fb[ind] -= dF
      Jb[np.ix_(ind,ind)] -= dJ

    # Stretching force and jacobian
    Fs = np.zeros( ndof )
    Js = np.zeros( (ndof,ndof) )
    for kEdge in range(edges.shape[0]):
      node0 = edges[kEdge, 0]
      node1 = edges[kEdge, 1]
      x0 = qNew[ 3*node0: 3*node0 + 3]
      x1 = qNew[ 3*node1: 3*node1 + 3]
      ind = [3*node0, 3*node0 + 1, 3*node0 + 2,
             3*node1, 3*node1 + 1, 3*node1 + 2]
      dF, dJ = gradEs_hessEs(x0, x1, refLen[kEdge], ks[kEdge])
      Fs[ind] -= dF
      Js[np.ix_(ind,ind)] -= dJ

    # Viscous force
    Fv = - visc * (qNew - qOld) / dt
    Jv = - visc / dt * np.eye(ndof)

    Forces = Fb + Fs + Fg + Fv # Sum of forces
    JForces = Jb + Js + Jv # Sum of Jacobians

    # Set up my equations of motion and calculating its residual (=0)
    f = massVector / dt * ( (qNew - qOld)/dt - uOld) - Forces # Residual of EOM
    J = massMatrix / dt ** 2 - JForces

    # Extract the free part of the f and J arrays
    f_free = f[freeIndex]
    J_free = J[np.ix_(freeIndex, freeIndex)]
    # Correction
    dq_free = np.linalg.solve(J_free, f_free)

    # Update my guess for position
    qNew[freeIndex] -= dq_free

    # Calculate error
    error = np.sum( np.abs(f_free))

    iter += 1

    # print('Iter = ', iter, ' error=', error)

  uNew = (qNew - qOld) / dt
  return qNew, uNew

"""#Main Discrete Shells

**DOFs and Nodes**
"""

# Beam / plate dimensions (from HW5)
l = 0.1      # free length [m]
w = 0.01     # width [m]
h = 0.002    # thickness [m]

# x-coordinates from the HW5 figure
x_coords = np.array([
    -0.0125, 0.0, 0.0125, 0.025, 0.0375,
    0.05, 0.0625, 0.075, 0.0875, 0.10
])
# two rows in y
y_coords = np.array([0.0, 0.01])

num_cols = len(x_coords)   # 10
num_rows = len(y_coords)   # 2
nv = num_cols * num_rows   # 20 nodes

# Build flat plate nodes at z = 0
nodes = np.zeros((nv, 3))
for r, y in enumerate(y_coords):
    for c, x in enumerate(x_coords):
        idx = r * num_cols + c
        nodes[idx, :] = np.array([x, y, 0.0])

# Flatten into DOF vector
qOld = nodes.reshape(-1)

ndof = 3 * nv
visc = 0.0001  # set to 0.01 for more damping

"""**Springs: Create edges (stretching) and hinges (bending)**"""

# --- Build triangles with alternating diagonals (as in HW5 figure) ---

triangles = []   # each row is (i,j,k) node indices, CCW looking from +z

for c in range(num_cols - 1):
    bl = 0 * num_cols + c       # bottom-left
    br = 0 * num_cols + (c + 1) # bottom-right
    tl = 1 * num_cols + c       # top-left
    tr = 1 * num_cols + (c + 1) # top-right

    if c % 2 == 0:
        # even cell: diagonal from top-left -> bottom-right
        # triangles: (bl, br, tl) and (tl, br, tr)
        triangles.append((bl, br, tl))
        triangles.append((tl, br, tr))
    else:
        # odd cell: diagonal from bottom-left -> top-right
        # triangles: (bl, br, tr) and (bl, tr, tl)
        triangles.append((bl, br, tr))
        triangles.append((bl, tr, tl))

triangles = np.array(triangles, dtype=int)

# --- Build stretching edges from triangles (unique undirected edges) ---

edges_set = set()
for (i, j, k) in triangles:
    for a, b in [(i, j), (j, k), (k, i)]:
        if a > b:
            a, b = b, a
        edges_set.add((a, b))

edges = np.array(sorted(list(edges_set)), dtype=int)

# --- Build hinges: every interior edge (shared by exactly 2 triangles) ---

edge_to_tris = {}  # maps edge -> list of triangle indices
for t_idx, (i, j, k) in enumerate(triangles):
    for a, b in [(i, j), (j, k), (k, i)]:
        key = tuple(sorted((a, b)))
        edge_to_tris.setdefault(key, []).append(t_idx)

hinges_list = []
for (a, b), tri_ids in edge_to_tris.items():
    if len(tri_ids) == 2:
        t0, t1 = tri_ids
        tri0 = triangles[t0]
        tri1 = triangles[t1]
        # third vertex of each triangle (the one not on edge a-b)
        c0 = [v for v in tri0 if v not in (a, b)][0]
        c1 = [v for v in tri1 if v not in (a, b)][0]
        # hinge is (x0, x1, x2, x3) with x0-x1 = hinge edge
        hinges_list.append((a, b, c0, c1))

hinges = np.array(hinges_list, dtype=int)

print("num triangles:", triangles.shape[0])
print("num edges:", edges.shape[0])
print("num hinges (interior edges):", hinges.shape[0])

plotShell(qOld, 0.0)

"""**Elastic Stiffness**"""

Y = 1.0e7   # Young's modulus [Pa]

kb = 2.0 / np.sqrt(3.0) * Y * h**3 / 12.0   # bending stiffness [N·m]
refLen = np.zeros(edges.shape[0])  # reference lengths l_k
ks = np.zeros_like(refLen)         # stretching stiffness
for kEdge in range(edges.shape[0]):
    node0 = edges[kEdge, 0]
    node1 = edges[kEdge, 1]
    x0 = qOld[3*node0:3*node0+3]
    x1 = qOld[3*node1:3*node1+3]
    refLen[kEdge] = np.linalg.norm(x1 - x0)
    ks[kEdge] = np.sqrt(3.0) / 2.0 * Y * h * (refLen[kEdge])**2

"""**Time parameters**"""

totalTime = 10 # seconds
dt = 0.001 # time step sie

tol = kb / (0.01) * 1e-3 # Approximate tolerance

"""**Mass Vector and Matrix**"""

rho = 1000.0  # kg/m^3
volume = l * w * h
totalM = rho * volume

dm = totalM / nv           # lumped mass per node
massVector = np.zeros(ndof)
for c in range(nv): # Loop over every node
  ind = [3*c, 3*c+1, 3*c+2] # location of the c-th node in the DOF vector
  massVector[ind] = dm

massMatrix = np.diag(massVector)

"""**External force**"""

g = np.array([0, 0, -9.8])
Fg = np.zeros(ndof)
for c in range(nv):
  ind = [3*c, 3*c+1, 3*c+2]
  Fg[ind] = massVector[ind] * g

"""**Natural curvature**"""

thetaBar = 0.0

"""**Boundary conditions and Initial Conditions**"""

uOld = np.zeros(ndof)

fixed_nodes = np.array([0, 1, 10, 11], dtype=int)  # four leftmost nodes
fixedIndex = []

for n in fixed_nodes:
    fixedIndex.extend([3*n, 3*n+1, 3*n+2])

fixedIndex = np.array(fixedIndex, dtype=int)
allIndex = np.arange(ndof)
freeIndex = np.setdiff1d(allIndex, fixedIndex)

"""**Time stepping loop**"""

Nsteps = int(round(totalTime / dt))
ctime = 0.0

# indices of tip nodes at x = l
bottom_tip = 0 * num_cols + (num_cols - 1)  # (0.1, 0)
top_tip    = 1 * num_cols + (num_cols - 1)  # (0.1, 0.01)

tipZ0 = 0.5 * (qOld[3*bottom_tip + 2] + qOld[3*top_tip + 2])  # = 0 initially
deltaZ = np.zeros(Nsteps)

for timeStep in range(Nsteps):
    # print('Current time = %f' % ctime)

    qNew, uNew = objfun(
        qOld, uOld, freeIndex, dt, tol,
        massVector, massMatrix,
        ks, refLen, edges,
        kb, thetaBar, hinges,
        Fg, visc
    )
    ctime += dt

    # Update
    qOld = qNew.copy()
    uOld = uNew.copy()

    # Tip displacement at centerline of free edge
    z_tip = 0.5 * (qNew[3*bottom_tip + 2] + qNew[3*top_tip + 2])
    deltaZ[timeStep] = z_tip - tipZ0

    # Plot every 100 steps if you like
    if timeStep % 500 == 0:
        plotShell(qOld, ctime)

# Visualize tip displacement vs time
plt.figure(2)
time_array = np.arange(1, Nsteps+1) * dt
plt.plot(time_array, deltaZ, 'ro-')
plt.box(True)
plt.xlabel('Time, t [s]')
plt.ylabel('Tip displacement, $\\delta_{\\text{plate}}(t)$ [m]')
plt.title('HW5: Tip displacement vs time')
plt.show()

# --- Euler–Bernoulli prediction and comparison ---
A = w * h                  # cross-sectional area
I = w * h**3 / 12.0        # second moment of area
q_uniform = rho * A * 9.8  # N/m, q = ρ A g

delta_EB = -q_uniform * l**4 / (8.0 * Y * I)

# Take steady value as the last sample (or mean of last 200 samples)
delta_plate_steady = np.mean(deltaZ[-200:])  # small smoothing window

print(f"Steady plate tip displacement δ_plate ≈ {delta_plate_steady:.4e} m")
print(f"Euler–Bernoulli prediction   δ_EB    ≈ {delta_EB:.4e} m")

rel_err = (delta_plate_steady - delta_EB) / delta_EB
print(f"Relative difference (δ_plate - δ_EB)/δ_EB ≈ {rel_err:.3%}")

# --- Plot: time history vs Euler–Bernoulli prediction ---
plt.figure()
plt.plot(time_array, deltaZ, label=r'Discrete shell $\delta_{\text{plate}}(t)$')
plt.axhline(delta_plate_steady, linestyle='--', label=r'Steady value $\bar{\delta}_{\text{plate}}$')
plt.axhline(delta_EB, linestyle=':', label=r'Euler–Bernoulli $\delta_{\text{EB}}$')

plt.xlabel('Time $t$ [s]')
plt.ylabel('Tip displacement $\\delta_z$ [m]')
plt.title('Tip displacement vs Euler–Bernoulli beam prediction')
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()

